import:
  label: Import Repo
  path: builder_site_import_path
  classes: code
  request_type: post
  confirm: Ready to import project?
update:
  label: Update Repo (git pull)
  path: builder_site_pull_path
  classes: download
  request_type: post
  confirm: Are you sure? This will stash any changes you have made.
symlinks:
  label: Generate Symlinks
  path: builder_site_symlink_path
  classes: link
  request_type: post
backup:
  label: Backup Database
  path: builder_site_backup_path
  classes: database
  request_type: post
  env: production
sync:
  label: Sync Database
  path: builder_site_sync_path
  classes: database
  request_type: post
  confirm: This is a destructive action. Proceed?
  env: development
