# rtsym:config/sites/default_site.yml
# 
# Site Config
# =================
# 
# This file is storing for all your site-specific configuration.
# 
# The values here are loaded into a nested OpenStruct, available via the 
# site_settings helper method, per environment. For example, if you have a 
# config like this:
# 
# development: &default
#   social:
#     facebook: "https://www.facebook.com/I_Am_Awesome"
# 
# Then you would get "https://www.facebook.com/I_Am_Awesome" by running:
# 
#     site_settings.social.facebook
# 
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
#
# WARNING: THIS FILE IS (AND SHOULD BE) TRACKED BY GIT. DO NOT PLACE ANY
# SENSITIVE INFORMATION IN THIS FILE.
# 
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
# 
development: &default
  say_hello: hello

test:
  <<: *default

production:
  <<: *default
