title: Hello World 123
slug: hello-world-123
templates:
  home:
    title: Home
    fields:
      subtitle:
        type: string
        label: Subtitle
      header_image:
        type: string
        label: Header Image
  about:
    title: About
    block: false
    fields:
      subtitle:
        type: string
        label: Subtitle
  feature:
    block: true
