# 
# Database Config
# =================
# 
# Replace the values here with your config, then copy to
# config/database.yml.
# 
# NOTE: How you set this up depends on whether you are
# working in development (writing code) or production
# (writing content).
# 
# Development (Code)
# -----------------
# 
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: [production_ip]
  username: [db_user]
  password: [db_pass]
  port: [mysql_port]
  socket: [mysql_socket]

development:
  <<: *default
  database: [db_name]

test:
  <<: *default
  database: [db_name]

# 
# Production (Content)
# -----------------
# 
production:
  adapter: mysql2
  encoding: utf8
  database: [db_name]
  pool: 5
  username: [db_user]
  password: [db_password]
  socket: /var/run/mysqld/mysqld.sock
